version: "3"
services: 
  goapp:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    tty: true
    volumes:
      - ./todo_app:/go/src/app
  mysql:
    build: ./mysql/
    volumes:
        - ./mysql/init:/docker-entrypoint-initdb.d
        - ./mysql/data:/var/lib/mysql
    environment: 
        - MYSQL_ROOT_PASSWORD=mysql
    ports:
        - "3306:3306"
